version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db
    networks:
      - backend

  db:
    image: oracle/database:19.3.0-ee
    environment:
      - ORACLE_PWD=oracle
    ports:
      - "1521:1521"
    networks:
      - backend

networks:
  backend:
    driver: bridge
