trigger:
- main  # Gatilho para rodar o pipeline quando mudanças forem feitas na branch main

pool:
  vmImage: 'ubuntu-latest'  # Imagem de build do pipeline

variables:
  imageName: 'api-dotnet'  # Nome da imagem Docker que será gerada

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET SDK'
      inputs:
        packageType: 'sdk'
        version: '8.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        containerRegistry: '<nome-do-registro-container>'  # Nome do seu Container Registry (ACR ou Docker Hub)
        repository: $(imageName)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'  # Local do seu Dockerfile
        tags: 'latest'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: AzureWebAppContainer@1
      displayName: 'Deploy Docker Image to Azure Web App'
      inputs:
        appName: '<nome-do-seu-app-service>'  # Nome do App Service no Azure
        containerRegistry: '<nome-do-registro-container>'  # Nome do seu Container Registry (ACR ou Docker Hub)
        imageName: '$(imageName):latest'  # Nome da imagem Docker gerada
        azureSubscription: '<nome-da-sua-assinatura-azure>'  # Assinatura do Azure

